shared:
  num_classes: &num_classes 4
  model_num_classes: &model_num_classes 5  # 4 classes + background
  num_epochs: &num_epochs 100
  validation_period: &val_period 5
  train_file: &train ./datasets/fruit-detection/dataset.json
  train_imgs_dir: &train_imgs_dir ./datasets/fruit-detection/data/images
  valid_file: &valid ./datasets/fruit-detection/dataset.json
  valid_imgs_dir: &valid_imgs_dir ./datasets/fruit-detection/data/images

runner:
  _target_: SSDDetectionRunner

engine:
  _target_: DeviceEngine

model:
  _target_: SingleShotDetector
  num_classes: *num_classes

loggers:
  console:
    _target_: ConsoleLogger

stages:
  initial_training:
    num_epochs: *num_epochs

    loaders: &loaders
      batch_size: 32
      num_workers: 4
      
      datasets:
        train:
          _target_: SSDDataset
          coco_json_path: *train
          images_dir: *train_imgs_dir
          transforms:
            _target_: albumentations.Compose
            transforms:
              - _target_: albu.Resize
                height: 300
                width: 300
              - _target_: albu.Normalize
              - _target_: albu.ToTensorV2
            bbox_params:
              _target_: albu.BboxParams
              format: albumentations

        valid:
          _target_: SSDDataset
          coco_json_path: *valid
          images_dir: *valid_imgs_dir
          transforms:
            _target_: albumentations.Compose
            transforms:
              - _target_: albu.Resize
                height: 300
                width: 300
              - _target_: albu.Normalize
              - _target_: albu.ToTensorV2
            bbox_params:
              _target_: albu.BboxParams
              format: albumentations

    criterion:
      _target_: SSDCriterion
      num_classes: *model_num_classes
      ignore_class: 0

    optimizer:
      _target_: AdamW
      lr: 0.001

    callbacks: &callbacks
      periodic_validation:
        _target_: PeriodicLoaderCallback
        valid_loader_key: valid
        valid_metric_key: mAP
        minimize: False
        valid: *val_period

      mAP:
        _target_: DetectionMeanAveragePrecision
        num_classes: *num_classes
        output_type: ssd
        iou_threshold: 0.5

      optimizer:
        _target_: OptimizerCallback
        metric_key: loss
