shared:
  image_size: &image_size 224
  resize_size: &resize_size 336 # int(image_size * 1.5)

stages:
  transform_params:
    _key_value: True

    train:
      transform: A.Compose
      transforms:
        - transform: A.SmallestMaxSize # also `albu.SmallestMaxSize` is allowed
          max_size: *resize_size
          p: 1.0
        - transform: A.RandomCrop
          height: *image_size
          width: *image_size
          p: 1.0
        - transform: A.RandomRotate90
        - transform: A.Cutout
        - transform: A.RandomBrightnessContrast
          brightness_limit: 0.2
          contrast_limit: 0.2
          p: 0.3
        - transform: A.GridDistortion
          p: 0.3
        - transform: A.HueSaturationValue
          p: 0.3
        - transform: A.Normalize
        - transform: A.ToTensor
    valid:
      transform: A.Compose
      transforms:
        - transform: A.CenterCrop
          height: *image_size
          width: *image_size
          p: 1.0
        - transform: A.Normalize
        - transform: A.ToTensor
