data_params:
  in_csv: null
  tag2class: null
  in_csv_infer: "./data/ants_bees/dataset.csv"
  datapath: "./data/ants_bees/"

args:
  batch_size: 64

stages: null
callbacks_params:
  loader:
    callback: CheckpointCallback
  infer:
    callback: InferCallback
