model_params:
  fp16: false       # general flag
  model: SimpleNet  # model from NETWORKS to use

args:
  workers: 0
  expdir: "mnist_simple"
  logdir: "./logs/mnist_simple"

stages:

  state_params:
    main_metric: &reduce_metric precision01
    minimize_metric: False

  criterion_params:
      criterion: CrossEntropyLoss

  optimizer_params:
      optimizer: Adam
      lr: 0.001
      weight_decay: 0.0001

  stage1:
    args:
      epochs: &train_epoch 3
      batch_size: 64

    callbacks_params:
      loss:
        callback: LossCallback
      optimizer:
        callback: OptimizerCallback
      precision:
        callback: PrecisionCallback
        precision_args: [1, 3, 5]
      scheduler:
        callback: OneCycleLR
        cycle_len: *train_epoch
        div: 3
        cut_div: 4
        momentum_range: [0.95, 0.85]
#      scheduler:
#        callback: SchedulerCallback
#        reduce_metric: *reduce_metric
      saver:
        callback: CheckpointCallback
      logger:
        callback: Logger
      tflogger:
        callback: TensorboardLogger
