FROM pytorch/pytorch:1.6.0-cuda10.1-cudnn7-devel

RUN apt-get update && apt-get install -y software-properties-common \
    && rm -rf /var/lib/apt/lists/* \
    && add-apt-repository "deb http://security.ubuntu.com/ubuntu xenial-security main" \
    && apt-get update && apt-get install -y \
        build-essential \
        libsm6 \
    	libxext6 \
    	libfontconfig1 \
    	libxrender1 \
        libswscale-dev \
        libtbb2 \
        libtbb-dev \
        libjpeg-dev \
        libpng-dev \
        libtiff-dev \
        libjasper-dev \
        libavformat-dev \
        libpq-dev \
    	libturbojpeg \
    	git \
	&& apt-get clean \
	&& rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

CMD mkdir -p /workspace

COPY requirements/ /workspace/
RUN pip install -r /workspace/requirements.txt --no-cache-dir \
    && pip install -r /workspace/requirements-cv.txt --no-cache-dir \
    && pip install -r /workspace/requirements-dev.txt --no-cache-dir \
    && pip install -r /workspace/requirements-ecosystem.txt --no-cache-dir \
    && pip install -r /workspace/requirements-log.txt --no-cache-dir \
    && pip install -r /workspace/requirements-ml.txt --no-cache-dir \
    && pip install -r /workspace/requirements-nlp.txt --no-cache-dir \
    && pip install -r /workspace/requirements-tune.txt --no-cache-dir \
    && pip install -r /workspace/requirements-hydra.txt --no-cache-dir

WORKDIR /workspace
