FROM pytorch/pytorch:1.3-cuda10.1-cudnn7-devel

RUN apt-get update && apt-get install -y \
    build-essential \
    libsm6 \
	libxext6 \
	libfontconfig1 \
	libxrender1 \
    libswscale-dev \
    libtbb2 \
    libtbb-dev \
    libjpeg-dev \
    libpng-dev \
    libtiff-dev \
    libjasper-dev \
    libavformat-dev \
    libpq-dev \
	libturbojpeg \
	software-properties-common \
	&& apt-get clean \
	&& rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

CMD mkdir -p /workspace

COPY requirements/ /workspace/
RUN pip install -r /workspace/requirements.txt --no-cache-dir \
    && pip install -r /workspace/requirements-rl.txt --no-cache-dir \
    && pip install -r /workspace/requirements-contrib.txt --no-cache-dir \
    && pip install -r /workspace/requirements-dev.txt --no-cache-dir

RUN git clone https://github.com/NVIDIA/apex \
    && pip install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./apex

WORKDIR /workspace
