FROM nvidia/cuda:10.1-cudnn7-devel-ubuntu16.04

RUN apt-get update && apt-get install -y software-properties-common \
    && rm -rf /var/lib/apt/lists/* \
    && add-apt-repository "deb http://security.ubuntu.com/ubuntu xenial-security main" \
    && apt-get update && apt-get install -y \
        build-essential \
        libsm6 \
    	libxext6 \
    	libfontconfig1 \
    	libxrender1 \
        libswscale-dev \
        libtbb2 \
        libtbb-dev \
        libjpeg-dev \
        libpng-dev \
        libtiff-dev \
        libjasper-dev \
        libavformat-dev \
        libpq-dev \
    	libturbojpeg \
    	software-properties-common \
        git \
        nano \
    	wget \
        psmisc \
        python3-dev \
        python3-setuptools \
	&& apt-get clean \
	&& rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# install python 3.6
RUN apt-get update && apt-get install -y software-properties-common \
    && rm -rf /var/lib/apt/lists/* \
    && add-apt-repository ppa:deadsnakes/ppa && \
    apt-get update && apt-get install -y \
        python3.6 \
        python3.6-dev \
        python3-pip \
    && ln -sfn /usr/bin/python3.6 /usr/bin/python3 \
    && ln -sfn /usr/bin/python3 /usr/bin/python \
    && ln -sfn /usr/bin/pip3 /usr/bin/pip

CMD mkdir -p /workspace

RUN pip install torch==1.4.0

WORKDIR /workspace
