FROM pytorch/pytorch:1.0-cuda10.0-cudnn7-devel

RUN apt-get update && apt-get install -y \
    build-essential \
    libsm6 \
	libxext6 \
	libfontconfig1 \
	libxrender1 \
    libswscale-dev \
    libtbb2 \
    libtbb-dev \
    libjpeg-dev \
    libpng-dev \
    libtiff-dev \
    libjasper-dev \
    libavformat-dev \
    libpq-dev \
	libturbojpeg \
	software-properties-common \
	&& apt-get clean \
	&& rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN pip install --no-cache-dir \
    numpy \
    pandas \
    sklearn \
    jpeg4py \
    opencv-python \
    tqdm \
    PyYAML \
    torchnet \
    redis \
    gym \
    catalyst \
    tensorboardX \
    crc32c

CMD mkdir -p /workspace
WORKDIR /workspace
