model_params:
  model: SimpleNet

args:
  expdir: "_tests_cv_classification"
  logdir: "./logs/cv_classification"

stages:

  data_params:
    batch_size: 64
    num_workers: 0

  state_params:
    main_metric: &reduced_metric accuracy01
    minimize_metric: False

  criterion_params:
      criterion: CrossEntropyLoss

  optimizer_params:
    optimizer: Adam
    lr: 0.001
    weight_decay: 0.0001

  scheduler_params:
    scheduler: MultiStepLR
    milestones: [1]
    gamma: 0.3

  stage1:
    state_params:
      num_epochs: 100

    callbacks_params:
      loss:
        callback: CriterionCallback
      optimizer:
        callback: OptimizerCallback
      accuracy:
        callback: AccuracyCallback
        accuracy_args: [1, 3, 5]
      scheduler:
        callback: SchedulerCallback
        reduced_metric: *reduced_metric
      saver:
        callback: CheckpointCallback
        save_n_best: 3
