version: 1
update_configs:
  - package_manager: "docker"
    directory: "/docker"
    update_schedule: "daily"
    ignored_updates:
      - match:
          dependency_name: "nvidia/cuda"
    default_labels:
      - "dependencies"
