model_params:
  model: SimpleNet

runner_params:
  input_key: image

args:
  expdir: "mnist_simple"
  logdir: "./logs/mnist_simple"

stages:

  data_params:
    batch_size: 64
    num_workers: 0

  transform_params:
    _key_value: True

    train:
      transform: A.Compose
      transforms:
        - transform: catalyst.TensorToImage
        - transform: A.Normalize
          mean: [0.1307]
          std: [0.3081]
        - transform: catalyst.ToTensor
    valid:
      transform: A.Compose
      transforms:
        - transform: catalyst.TensorToImage
        - transform: A.Normalize
          mean: [0.1307]
          std: [0.3081]
        - transform: catalyst.ToTensor

  state_params:
    main_metric: &reduce_metric accuracy01
    minimize_metric: False

  criterion_params:
      criterion: CrossEntropyLoss

  optimizer_params:
    optimizer: Adam
    lr: 0.001
    weight_decay: 0.0001

  scheduler_params:
    scheduler: MultiStepLR
    milestones: [1]
    gamma: 0.3

  stage1:
    state_params:
      num_epochs: &num_epochs 3

    callbacks_params:
      loss:
        callback: CriterionCallback
      optimizer:
        callback: OptimizerCallback
      accuracy:
        callback: AccuracyCallback
        accuracy_args: [1, 3, 5]
      scheduler:
        callback: SchedulerCallback
        reduce_metric: *reduce_metric
      saver:
        callback: CheckpointCallback
        save_n_best: 3
