name: torch 1.1
on: [pull_request]

jobs:
   check-examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6

      - name: check examples
        run: bash teamcity/dl_cpu_110.sh
